# The folders below will be cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - apt-cache/
  - vendor/

before_script:

  # Install git, the php image doesn't have installed. Cache apt packages between stages.
  - export APT_CACHE_DIR=`pwd`/apt-cache && mkdir -pv $APT_CACHE_DIR
  - apt-get update -yqq
  - apt-get -o dir::cache::archives="$APT_CACHE_DIR" install git subversion zip unzip -yqq

  # Install composer
  - curl -sS https://getcomposer.org/installer | php
  - mv composer.phar /usr/local/bin/composer

stages:
  - inspect
  - tests

inspect:
  image: php:7.0
  stage: inspect
  script:
    # Install all project dependencies
    - composer install --ignore-platform-reqs
    - ./vendor/bin/phing inspect

tests:5.6:
  image: php:5.6
  stage: tests
  script:
    # Install all project dependencies
    - composer install --ignore-platform-reqs
    - ./vendor/bin/phing tests:init
    - ./vendor/bin/phing tests

tests:7.0:
  image: php:7.0
  stage: tests
  script:
    # Install all project dependencies
    - composer install --ignore-platform-reqs
    - ./vendor/bin/phing tests:init
    - ./vendor/bin/phing tests

tests:7.1:
  image: php:7.1
  stage: tests
  script:
    # Install all project dependencies
    - composer install --ignore-platform-reqs
    - ./vendor/bin/phing tests:init
    - ./vendor/bin/phing tests
